config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'about'   => 'static_pages#about'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'index_tag'   => 'tags#index'
  get    'show_tag'   => 'tags#show'
  get    'new_tag'   => 'tags#new'
  post   'create_tag'   => 'tags#create'
  delete 'destroy_tag'  => 'tags#destroy'
  get    'index_post'   => 'posts#index'
  get    'show_post'   => 'posts#show'
  get    'new_post'   => 'posts#new'
  post   'create_post'   => 'posts#create'
  delete 'destroy_post'  => 'posts#destroy'

  resources :users
  resources :posts
  resources :tags
  resources :subscriptions,       only: [:create, :destroy]

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :taggings
  has_many :tag, through: :taggings

  validates :subject,  presence: true
  validates :description,  presence: true
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :subscriptions
    has_many :users, through: :subscriptions
    has_many :taggings
    has_many :posts, through: :taggings

    validates :name,  presence: true


end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :subscriptions
  has_many :tags, through: :subscriptions
  has_many :tags_posts, :through =>:tags, :source =>:posts

  validates :name,  presence: true, length: { minimum: 4, maximum: 30 }, uniqueness: { case_sensitive: false }
  
  validates :email, presence: true, length: { maximum: 100 }, uniqueness: true, 
	           format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    
  has_secure_password
  
  validates :password, confirmation: true, length: { minimum: 4, maximum: 30 }
  validates :password_confirmation, presence: true


  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end


  def follow(tag)
    subscriptions.create(tag_id: tag.id)
  end

  def unfollow(tag)
    subscriptions.find_by(tag_id: tag.id).destroy
  end

  def following?(tag)
    !subscriptions.find_by(tag_id: tag.id).nil?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
  def admin_user
      redirect_to(root_url) unless current_user.admin?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :admin_user, only: [:new, :create, :destroy]
  before_action :logged_in_user, only: [:index, :show]

  def index
    @posts = Post.paginate(page: params[:page])
  end
  
  def show
    @post = Post.find(params[:id]) 
  end
  
  def new
    @post     = Post.new
    @all_tags = Tag.all
    @post_tag = @post.taggings.build
  end
  
  def create
  	@post = Post.new(post_params)
    params[:tags][:id].each do |tag|
    @post.taggings.build(:tag_id => tag)
    end

    if @post.save
      flash[:success] = "Micropost created!"
      redirect_to index_post_path
    else
      @feed_items = []
      render 'new'
    end
  end
  
  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "Post deleted"
    redirect_to request.referrer || root_url
  end
  
  private
    
    def post_params
      params.require(:post).permit(:subject, :description, :tag_id)
    end    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
        log_in user
        redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in? 
      @post_items = current_user.tags_posts.reverse      
     end
  end

  def about
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :logged_in_user

  def create
    @tag = Tag.find(params[:tag_id])
    current_user.follow(@tag)
    redirect_to @tag 
  end
  
  def destroy
    @tag = Subscription.find(params[:id]).tag
    current_user.unfollow(@tag)
    redirect_to @tag
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :logged_in_user, only: [:index, :show]
  before_action :admin_user, only: [:new, :create, :destroy]
  

  def index
    #@tags=Tag.all
    @tags = Tag.paginate(page: params[:page])
  end
  
  def show
    @tag = Tag.find(params[:id])

  end
  
  def new
    @tag = Tag.new
  end
  
  def create
  	@tag = Tag.new(tag_params)
    if @tag.save
      flash[:success] = "tag created!"
      redirect_to index_tag_path
    else
      @feed_items = []
      render 'new'
    end
  end
  
  def destroy
    Tag.find(params[:id]).destroy
    flash[:success] = "Tag deleted"
    redirect_to request.referrer || root_url
  end

  
  private
    
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:info] = "Sign up Successful."

      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit

  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  
  private
    
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "newsletter", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Tag", index_tag_path %></li>

           <% if current_user.admin? %>
            <li><%= link_to "Post", index_post_path %></li>
            <li><%= link_to "Users", users_path %></li>
           <% end %>
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
           <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newsletter</title>
    <%= stylesheet_link_tag    'application', media: 'all', 
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>

    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<li>
<span class="content">
  <%= link_to post.subject, post %>
  <% if current_user.admin? %>
    | <%= link_to "delete",post,  method: :delete ,
                                  data: { confirm: "You sure?" } %>
  <% end %>
  </span>
  <br>

  <span class="stamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
</li>

app/views/posts/index.html.erb
<% provide(:title, 'All posts') %>
<center><h3><%= link_to "Add New Post", new_post_path %></h3></center>
<h1>All Posts</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @posts %>
</ul>

<%= will_paginate %>

app/views/posts/new.html.erb
<% provide(:title, 'Add a News') %>
<h1>Add a News</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@post) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    
      <%= f.label :subject %>
      <%= f.text_field :subject, class: 'form-control' %>
      
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= fields_for(@post_tag) do |ab| %>
      <%= ab.label 'All tag' %>
      <%= collection_select(:tags, :id, @all_tags, :id, :name, {}, {:multiple => true}) %>
     <% end %>
      
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, 'News') %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @post.subject %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
      <h3>
        <%= @post.description %>
      </h3>
  
   </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @post_items.any? %>
  <ol class="microposts">
  <h4>
    <%= render @post_items %>
    </h4>
  </ol>
<% end %>  

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
Newsletter app
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <div class="col-md-12">
      <h1>Newsletter</h1> 
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Newsletter</h1>
    
    
    <%= link_to "Sign up now", signup_path, class: "btn btn-lg btn-primary" %>  
  </div>

<% end %>

app/views/tags/_follow.html.erb
<%= form_for(current_user.subscriptions.build) do |f| %>
  <div><%= hidden_field_tag :tag_id, @tag.id %></div>                       
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/tags/_follow_form.html.erb
<% unless current_user?(@tag) %>
  <div id="follow_form">
    <% if current_user.following?(@tag) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<li>
  <%= link_to tag.name, tag %>
  <% if current_user.admin? %>
    | <%= link_to "delete",tag,  method: :delete ,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/tags/_unfollow.html.erb
<%= form_for(current_user.subscriptions.find_by(tag_id: @tag.id),
             html: { method: :delete }) do |f| %>                       
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/tags/index.html.erb
<% provide(:title, 'All Tags') %>
<% if current_user.admin? %>
<center><h3><%= link_to "Add New Tag", new_tag_path %></h3></center>
<% end %>
<h1>All Tag</h1>
<%= will_paginate %>

<ul class="users">
  <%= render @tags %>
</ul>

<%= will_paginate %>

app/views/tags/new.html.erb
<% provide(:title, 'Add a Tag') %>
<h1>Add a Tag</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@tag) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tags/show.html.erb
<% provide(:title, 'All Tags') %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @tag.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
     <%= render 'follow_form' if logged_in? %>
  </div>
</div>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    
  </div>
</div>